/**
 * Fallback code templates for Prisma Schema, Next.js API Routes, and React 19 UI.
 * Used when OpenRouter LLM generation is unavailable or offline.
 */

export function generateSmartEnglishPrismaSchema(prompt: string, _nodesSummary?: string): string {
  const p = prompt.toLowerCase();
  const hasTasks = p.includes("todo") || p.includes("task") || p.includes("tehtäv");
  const hasOrders = p.includes("order") || p.includes("payment") || p.includes("maksu") || p.includes("tilaus");

  return `// Prisma Database Schema
// Generated by Agentic Architect
// Datasource: SQLite

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

enum Role {
  USER
  ADMIN
}

enum ProjectStatus {
  PLANNING
  IN_PROGRESS
  COMPLETED
  ARCHIVED
}

model User {
  id        String   @id @default(uuid())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
${hasTasks ? `  tasks     Task[]\n` : ""}${hasOrders ? `  orders    Order[]\n` : ""}  projects  Project[]
}

model Project {
  id           String        @id @default(uuid())
  name         String
  description  String?
  status       ProjectStatus @default(PLANNING)
  ownerId      String
  owner        User          @relation(fields: [ownerId], references: [id], onDelete: Cascade)
  createdAt    DateTime      @default(now())
  updatedAt    DateTime      @updatedAt
}
${
  hasTasks
    ? `
model Task {
  id          String   @id @default(uuid())
  title       String
  description String?
  completed   Boolean  @default(false)
  userId      String
  user        User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
`
    : ""
}${
  hasOrders
    ? `
model Order {
  id        String   @id @default(uuid())
  amount    Float
  status    String   @default("PENDING")
  userId    String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`
    : ""
}`;
}

export async function generateSmartEnglishApiCode(
  prompt: string,
  _nodesSummary?: string,
  _prismaSchema?: string | null
): Promise<string> {
  const p = prompt.toLowerCase();
  const hasTasks = p.includes("todo") || p.includes("task") || p.includes("tehtäv");
  const hasOrders = p.includes("order") || p.includes("payment") || p.includes("maksu") || p.includes("tilaus");
  const entityName = hasTasks ? "Task" : hasOrders ? "Order" : "Project";
  const entityPlural = hasTasks ? "tasks" : hasOrders ? "orders" : "projects";

  return `// Next.js App Router Backend Endpoints & Server Actions
// Generated by Agentic Architect - Data Gate 2
// Language: Standard English

import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";

// ==========================================
// 1. Uniform Response Envelopes & Types
// ==========================================
export type ApiResponse<T> =
  | { success: true; data: T }
  | { success: false; error: { code: string; message: string; details?: unknown } };

// ==========================================
// 2. Zod Validation Schemas
// ==========================================
export const Create${entityName}Schema = z.object({
  title: z.string().min(1, "Title is required").max(120),
  description: z.string().max(1000).optional(),
  userId: z.string().uuid("Invalid user identifier").optional(),
${hasOrders ? `  amount: z.number().positive("Amount must be greater than zero"),\n` : ""}});

export const Update${entityName}Schema = Create${entityName}Schema.partial().extend({
  id: z.string().uuid("Invalid identifier"),
${hasTasks ? `  completed: z.boolean().optional(),\n` : ""}});

export type Create${entityName}Input = z.infer<typeof Create${entityName}Schema>;
export type Update${entityName}Input = z.infer<typeof Update${entityName}Schema>;

// ==========================================
// 3. Next.js Route Handlers (app/api/${entityPlural}/route.ts)
// ==========================================

/**
 * GET /api/${entityPlural}
 * Fetches a list of ${entityPlural} with pagination and security guards
 */
export async function GET(request: Request): Promise<NextResponse<ApiResponse<any[]>>> {
  try {
    const { searchParams } = new URL(request.url);
    const limit = Math.min(parseInt(searchParams.get("limit") || "50", 10), 100);

    // Fetch from database using Prisma
    const items = await (prisma as any).${entityName.toLowerCase()}.findMany({
      take: limit,
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json({
      success: true,
      data: items,
    });
  } catch (error: any) {
    console.error("GET /api/${entityPlural} error:", error);
    return NextResponse.json(
      {
        success: false,
        error: {
          code: "INTERNAL_SERVER_ERROR",
          message: error.message || "Failed to retrieve ${entityPlural}",
        },
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/${entityPlural}
 * Creates a new ${entityName.toLowerCase()} with Zod input validation
 */
export async function POST(request: Request): Promise<NextResponse<ApiResponse<any>>> {
  try {
    const body = await request.json();
    const validatedData = Create${entityName}Schema.safeParse(body);

    if (!validatedData.success) {
      return NextResponse.json(
        {
          success: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Request payload failed schema validation",
            details: validatedData.error.flatten(),
          },
        },
        { status: 400 }
      );
    }

    const newItem = await (prisma as any).${entityName.toLowerCase()}.create({
      data: validatedData.data,
    });

    return NextResponse.json({ success: true, data: newItem }, { status: 201 });
  } catch (error: any) {
    console.error("POST /api/${entityPlural} error:", error);
    return NextResponse.json(
      {
        success: false,
        error: {
          code: "CREATION_FAILED",
          message: error.message || "Failed to create ${entityName.toLowerCase()}",
        },
      },
      { status: 500 }
    );
  }
}

// ==========================================
// 4. Next.js Server Actions (src/app/actions/${entityPlural}.ts)
// ==========================================

/**
 * Server Action: Creates a new ${entityName} directly with instant cache revalidation
 */
export async function create${entityName}Action(rawData: unknown): Promise<ApiResponse<any>> {
  const result = Create${entityName}Schema.safeParse(rawData);
  if (!result.success) {
    return {
      success: false,
      error: {
        code: "INVALID_INPUT",
        message: "Validation failed",
        details: result.error.flatten(),
      },
    };
  }

  try {
    const created = await (prisma as any).${entityName.toLowerCase()}.create({
      data: result.data,
    });

    revalidatePath("/${entityPlural}");
    return { success: true, data: created };
  } catch (err: any) {
    return {
      success: false,
      error: {
        code: "DATABASE_ERROR",
        message: err.message || "Failed to save ${entityName.toLowerCase()} to database",
      },
    };
  }
}
`;
}

export async function generateSmartEnglishUiCode(
  prompt: string,
  _nodesSummary?: string,
  _prismaSchema?: string | null,
  _apiCode?: string | null
): Promise<string> {
  const p = prompt.toLowerCase();
  const hasTasks = p.includes("todo") || p.includes("task") || p.includes("tehtäv");
  const hasOrders = p.includes("order") || p.includes("payment") || p.includes("maksu") || p.includes("tilaus");
  const entityName = hasTasks ? "Task" : hasOrders ? "Order" : "Project";
  const entityPlural = hasTasks ? "Tasks" : hasOrders ? "Orders" : "Projects";

  return `"use client";

import React, { useState, useTransition } from "react";
import {
  Sparkles,
  Plus,
  Search,
  CheckCircle2,
  Clock,
  Trash2,
  TrendingUp,
  LayoutGrid,
  Filter,
  Check,
  AlertCircle,
  X,
  Loader2,
  ArrowUpRight,
} from "lucide-react";

export interface ${entityName}Item {
  id: string;
  title: string;
  description?: string;
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
  createdAt: string;
${hasOrders ? "  amount?: number;\n" : ""}
}

const INITIAL_${entityPlural.toUpperCase()}: ${entityName}Item[] = [
  {
    id: "1",
    title: "Setup modern cloud infrastructure",
    description: "Initialize serverless edge runtimes, database migrations, and CI pipelines.",
    status: "COMPLETED",
    createdAt: "2026-09-10",
${hasOrders ? "    amount: 250,\n" : ""}  },
  {
    id: "2",
    title: "Implement secure authentication flow",
    description: "Configure NextAuth session encryption and role-based route middleware.",
    status: "IN_PROGRESS",
    createdAt: "2026-09-12",
${hasOrders ? "    amount: 490,\n" : ""}  },
  {
    id: "3",
    title: "Deliver production performance benchmark",
    description: "Run Core Web Vitals audit and database query optimization checks.",
    status: "PENDING",
    createdAt: "2026-09-14",
${hasOrders ? "    amount: 180,\n" : ""}  },
];

export default function ${entityName}Dashboard() {
  const [items, setItems] = useState<${entityName}Item[]>(INITIAL_${entityPlural.toUpperCase()});
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<"ALL" | "PENDING" | "IN_PROGRESS" | "COMPLETED">("ALL");
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDescription, setNewDescription] = useState("");
${hasOrders ? '  const [newAmount, setNewAmount] = useState("100");\n' : ""}  const [isPending, startTransition] = useTransition();

  // Filter items
  const filteredItems = items.filter((item) => {
    const matchesSearch =
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (item.description && item.description.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesStatus = statusFilter === "ALL" || item.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  // Calculate stats
  const totalCount = items.length;
  const completedCount = items.filter((i) => i.status === "COMPLETED").length;
  const inProgressCount = items.filter((i) => i.status === "IN_PROGRESS").length;
  const pendingCount = items.filter((i) => i.status === "PENDING").length;
  const completionRate = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  const handleCreate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;

    startTransition(() => {
      const newItem: ${entityName}Item = {
        id: (items.length + 1).toString(),
        title: newTitle.trim(),
        description: newDescription.trim() || undefined,
        status: "PENDING",
        createdAt: new Date().toISOString().split("T")[0],
${hasOrders ? "        amount: parseFloat(newAmount) || 0,\n" : ""}      };

      setItems([newItem, ...items]);
      setNewTitle("");
      setNewDescription("");
${hasOrders ? '      setNewAmount("100");\n' : ""}      setIsModalOpen(false);
    });
  };

  const handleToggleStatus = (id: string) => {
    setItems((prev) =>
      prev.map((item) => {
        if (item.id !== id) return item;
        const nextStatus: ${entityName}Item["status"] =
          item.status === "PENDING"
            ? "IN_PROGRESS"
            : item.status === "IN_PROGRESS"
            ? "COMPLETED"
            : "PENDING";
        return { ...item, status: nextStatus };
      })
    );
  };

  const handleDelete = (id: string) => {
    setItems((prev) => prev.filter((i) => i.id !== id));
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 p-6 sm:p-8 space-y-8 font-sans">
      {/* Top Header */}
      <header className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-zinc-800/80 pb-6">
        <div>
          <div className="flex items-center space-x-2 text-purple-400 text-xs font-semibold uppercase tracking-wider mb-1">
            <Sparkles className="h-4 w-4" />
            <span>Production Feature Module</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            ${entityName} Management Hub
          </h1>
          <p className="text-sm text-zinc-400 mt-1">
            Modern high-performance interface with reactive state and instant caching.
          </p>
        </div>

        <button
          onClick={() => setIsModalOpen(true)}
          className="flex items-center space-x-2 px-4 py-2.5 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium rounded-xl shadow-lg shadow-purple-900/30 transition-all hover:scale-[1.02]"
        >
          <Plus className="h-4 w-4" />
          <span>New ${entityName}</span>
        </button>
      </header>

      {/* KPI Stats Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800/80">
          <div className="flex items-center justify-between text-zinc-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Total ${entityPlural}</span>
            <LayoutGrid className="h-4 w-4 text-purple-400" />
          </div>
          <div className="text-2xl font-bold text-white">{totalCount}</div>
        </div>

        <div className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800/80">
          <div className="flex items-center justify-between text-zinc-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">In Progress</span>
            <Clock className="h-4 w-4 text-amber-400" />
          </div>
          <div className="text-2xl font-bold text-white">{inProgressCount}</div>
        </div>

        <div className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800/80">
          <div className="flex items-center justify-between text-zinc-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Completed</span>
            <CheckCircle2 className="h-4 w-4 text-emerald-400" />
          </div>
          <div className="text-2xl font-bold text-white">{completedCount}</div>
        </div>

        <div className="p-4 rounded-2xl bg-zinc-900/60 border border-zinc-800/80">
          <div className="flex items-center justify-between text-zinc-400 mb-2">
            <span className="text-xs font-medium uppercase tracking-wider">Completion Rate</span>
            <TrendingUp className="h-4 w-4 text-purple-400" />
          </div>
          <div className="text-2xl font-bold text-white">{completionRate}%</div>
        </div>
      </div>

      {/* Controls Bar: Search & Filter */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-zinc-500" />
          <input
            type="text"
            placeholder="Search ${entityPlural.toLowerCase()}..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-zinc-900/60 border border-zinc-800/80 rounded-xl text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-purple-500 transition-colors"
          />
        </div>

        <div className="flex items-center space-x-1.5 p-1 bg-zinc-900/60 border border-zinc-800/80 rounded-xl text-xs">
          {(["ALL", "PENDING", "IN_PROGRESS", "COMPLETED"] as const).map((status) => (
            <button
              key={status}
              onClick={() => setStatusFilter(status)}
              className={\`px-3 py-1.5 rounded-lg font-medium transition-all \${
                statusFilter === status
                  ? "bg-purple-600 text-white shadow-sm"
                  : "text-zinc-400 hover:text-white"
              }\`}
            >
              {status === "ALL" ? "All" : status.replace("_", " ")}
            </button>
          ))}
        </div>
      </div>

      {/* List / Table of Items */}
      <div className="rounded-2xl border border-zinc-800/80 bg-zinc-900/40 overflow-hidden shadow-xl">
        {filteredItems.length === 0 ? (
          <div className="p-12 text-center text-zinc-500 text-sm">
            No ${entityPlural.toLowerCase()} found matching your criteria.
          </div>
        ) : (
          <div className="divide-y divide-zinc-800/60">
            {filteredItems.map((item) => (
              <div
                key={item.id}
                className="p-4 sm:p-5 flex items-center justify-between gap-4 hover:bg-zinc-800/30 transition-colors"
              >
                <div className="flex items-start space-x-3.5 min-w-0">
                  <button
                    onClick={() => handleToggleStatus(item.id)}
                    className={\`mt-0.5 w-5 h-5 rounded-lg border flex items-center justify-center transition-all \${
                      item.status === "COMPLETED"
                        ? "bg-emerald-500 border-emerald-500 text-black"
                        : item.status === "IN_PROGRESS"
                        ? "border-amber-400 text-amber-400"
                        : "border-zinc-700 text-transparent hover:border-zinc-500"
                    }\`}
                  >
                    <Check className="h-3 w-3" />
                  </button>

                  <div className="min-w-0">
                    <h3
                      className={\`text-sm font-semibold tracking-tight \${
                        item.status === "COMPLETED" ? "line-through text-zinc-500" : "text-zinc-100"
                      }\`}
                    >
                      {item.title}
                    </h3>
                    {item.description && (
                      <p className="text-xs text-zinc-400 mt-0.5 line-clamp-1">{item.description}</p>
                    )}
                  </div>
                </div>

                <div className="flex items-center space-x-4 shrink-0">
                  <span
                    className={\`text-[11px] font-semibold px-2.5 py-1 rounded-full \${
                      item.status === "COMPLETED"
                        ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                        : item.status === "IN_PROGRESS"
                        ? "bg-amber-500/10 text-amber-400 border border-amber-500/20"
                        : "bg-zinc-800 text-zinc-400 border border-zinc-700"
                    }\`}
                  >
                    {item.status.replace("_", " ")}
                  </span>

                  <button
                    onClick={() => handleDelete(item.id)}
                    className="p-1.5 text-zinc-500 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-colors"
                    title="Delete item"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Modal Dialog for New Item */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-zinc-900 border border-zinc-800 rounded-2xl max-w-md w-full p-6 space-y-4 shadow-2xl animate-in zoom-in-95">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-bold text-white">Create New ${entityName}</h2>
              <button
                onClick={() => setIsModalOpen(false)}
                className="text-zinc-400 hover:text-white"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <form onSubmit={handleCreate} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-zinc-300 mb-1">Title</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. Implement user workspace permissions"
                  className="w-full px-3 py-2 bg-zinc-950 border border-zinc-800 rounded-xl text-xs text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-purple-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-zinc-300 mb-1">Description</label>
                <textarea
                  rows={3}
                  value={newDescription}
                  onChange={(e) => setNewDescription(e.target.value)}
                  placeholder="Detailed engineering notes or criteria..."
                  className="w-full px-3 py-2 bg-zinc-950 border border-zinc-800 rounded-xl text-xs text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-purple-500"
                />
              </div>

              <div className="flex items-center justify-end space-x-2 pt-3 border-t border-zinc-800">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 text-xs text-zinc-400 hover:text-white rounded-xl"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isPending}
                  className="flex items-center space-x-1.5 px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold rounded-xl transition-all"
                >
                  {isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />}
                  <span>Create ${entityName}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
`;
}
